const { Document, Packer, Paragraph, Table, TableRow, TableCell, TextRun, HeadingLevel, WidthType, AlignmentType, ShadingType } = require('docx');
const fs = require('fs');

const hdr = (text, level) => new Paragraph({ text, heading: level, spacing: { before: 300, after: 150 } });
const p = (text) => new Paragraph({ children: [new TextRun({ text, size: 22 })], spacing: { after: 100 } });
const b = (text) => new Paragraph({ children: [new TextRun({ text, size: 22 })], bullet: { level: 0 }, spacing: { after: 80 } });
const mono = (text) => new Paragraph({ children: [new TextRun({ text, font: 'Courier New', size: 20 })], shading: { type: ShadingType.CLEAR, fill: 'F0F0F0' }, spacing: { after: 60 } });
const gap = () => new Paragraph({ text: '', spacing: { after: 150 } });
const hr = () => new Paragraph({ border: { bottom: { style: 'single', size: 6, color: '2E4057' } }, spacing: { before: 200, after: 200 } });

const hCell = (text) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text, bold: true, color: 'FFFFFF', size: 20 })] })], shading: { type: ShadingType.CLEAR, fill: '2E4057' }, margins: { top: 80, bottom: 80, left: 100, right: 100 } });
const dCell = (text) => new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: String(text), size: 20 })] })], margins: { top: 80, bottom: 80, left: 100, right: 100 } });
const tbl = (headers, rows) => new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [new TableRow({ children: headers.map(hCell), tableHeader: true }), ...rows.map(r => new TableRow({ children: r.map(dCell) }))] });

const doc = new Document({
  creator: 'AIS', title: 'Alumni Information System Documentation',
  sections: [{ children: [
    new Paragraph({ children: [new TextRun({ text: 'Alumni Information System (AIS)', bold: true, size: 52, color: '2E4057' })], alignment: AlignmentType.CENTER, spacing: { after: 100 } }),
    new Paragraph({ children: [new TextRun({ text: 'Complete Project Documentation  |  Node.js + Express + MySQL  |  University of Hyderabad', size: 22, color: '666666' })], alignment: AlignmentType.CENTER, spacing: { after: 400 } }),
    hr(),

    hdr('1. Project Overview', HeadingLevel.HEADING_1),
    tbl(['Field','Detail'],[
      ['Project Name','Alumni Information System (AIS)'],
      ['Type','Full-Stack Web Application'],
      ['Purpose','Platform connecting alumni, students and administrators of University of Hyderabad'],
      ['Domain Restriction','Only @uohyd.ac.in email addresses can register (admin exempt)'],
      ['Default Admin','admin@alumni.com / Admin@123'],
      ['Server Port','5000 (configurable via .env)'],
      ['Run Command','npm run dev  (nodemon)  or  npm start'],
      ['Database','MySQL — alumni_db'],
      ['License','MIT'],
    ]),
    gap(), hdr('What the System Offers', HeadingLevel.HEADING_3),
    b('Alumni Directory — searchable profiles of all alumni'),
    b('Event Management — college events, reunions, seminars'),
    b('Job Board — alumni post opportunities for students'),
    b('Messaging — direct peer-to-peer chat between any registered users'),
    b('Role-Based Access — Admin, Alumni, Student with different permissions'),
    b('Admin Dashboard — live system statistics and user management'),
    b('Admin Helpdesk — admin can initiate or reply to conversations with any user'),
    b('Floating Widget — contact admin chat overlay on all user pages'),
    hr(),

    hdr('2. Tech Stack (Complete Breakdown)', HeadingLevel.HEADING_1),
    tbl(['Layer','Technology','Version / Detail','Purpose'],[
      ['Backend','Node.js','Runtime','JavaScript server-side execution'],
      ['Backend','Express.js','^4.18.2','HTTP web framework, routing, middleware'],
      ['Backend','mysql2','^3.22.3','MySQL driver — async connection pool'],
      ['Backend','bcryptjs','^2.4.3','Password hashing (salt rounds = 10)'],
      ['Backend','jsonwebtoken','^9.0.2','JWT generation & verification'],
      ['Backend','dotenv','^16.4.5','Environment variable management'],
      ['Backend','cors','^2.8.5','Cross-Origin Resource Sharing'],
      ['Backend','nodemon','^3.0.3','Auto-restart during development'],
      ['Database','MySQL','v8+ / port 3306','Relational DBMS'],
      ['Database','Database Name','alumni_db','Target database'],
      ['Database','Connection','Pool limit: 10','mysql2.createPool'],
      ['Database','Schema Setup','schema.sql','node scripts/setupDb.js'],
      ['Frontend','HTML5','—','Page structure (9 pages)'],
      ['Frontend','Bootstrap 5.3','CDN','Responsive layout, components'],
      ['Frontend','Vanilla CSS','style.css','Custom styles (cards, chat UI, layout)'],
      ['Frontend','Vanilla JavaScript','api.js','DOM manipulation, API calls, auth logic'],
      ['Frontend','Fetch API','—','Async HTTP requests to backend'],
      ['Frontend','localStorage','—','JWT token + user object persistence'],
      ['Dev Env','OS','Windows','Development platform'],
      ['Dev Env','Editor','VS Code','Code editor'],
      ['Dev Env','API Testing','Postman','REST API testing tool'],
      ['Dev Env','Package Manager','npm','Dependency management'],
    ]),
    hr(),

    hdr('3. System Architecture', HeadingLevel.HEADING_1),
    tbl(['Layer','Component','Responsibility'],[
      ['Client','HTML Pages + api.js','UI rendering, Fetch API calls, JWT storage'],
      ['Transport','HTTP / REST (JSON)','Request/response between browser and server'],
      ['Server','Express (server.js : 5000)','CORS, JSON parser, static file serving'],
      ['Routing','/api/auth, /api/alumni, /api/events, /api/jobs, /api/messages, /api/admin','URL to controller mapping'],
      ['Middleware','auth.js — protect() + authorise()','JWT verification and role-based guard'],
      ['Controllers','authController, alumniController, eventController, jobController, messageController, adminController','Business logic and DB queries'],
      ['Database','MySQL — alumni_db','users, alumni_profiles, events, jobs, messages'],
    ]),
    gap(),
    b('MVC-like: Routes → Middleware → Controllers → Database'),
    b('REST API with JSON responses'),
    b('SPA-style Frontend: Single-page navigation, catch-all serves index.html'),
    b('Stateless Auth: JWT stored in localStorage, sent as Bearer header'),
    hr(),

    hdr('4. Project Folder Structure', HeadingLevel.HEADING_1),
    mono('alumni-system/'),
    mono('├── server.js               ← App entry point'),
    mono('├── package.json            ← Dependencies & scripts'),
    mono('├── .env                    ← Environment variables (secret)'),
    mono('├── config/db.js            ← MySQL Pool connection'),
    mono('├── middleware/auth.js      ← JWT protect() + Role authorise()'),
    mono('├── controllers/'),
    mono('│   ├── authController.js   ← register, login, getMe, getAdminId'),
    mono('│   ├── alumniController.js ← getAllAlumni, getById, updateProfile'),
    mono('│   ├── eventController.js  ← CRUD events'),
    mono('│   ├── jobController.js    ← CRUD jobs (ownership check)'),
    mono('│   ├── messageController.js← send, inbox, conversation, mark-read'),
    mono('│   └── adminController.js  ← dashboard stats, user CRUD, helpdesk'),
    mono('├── routes/  (auth, alumni, events, jobs, messages, admin)'),
    mono('├── scripts/schema.sql      ← DB schema + seed admin'),
    mono('├── scripts/setupDb.js      ← DB setup runner'),
    mono('└── public/                 ← Frontend static files (9 HTML pages + css + js)'),
    hr(),

    hdr('5. Database Design', HeadingLevel.HEADING_1),
    hdr('users — Core user table', HeadingLevel.HEADING_3),
    tbl(['Column','Type','Notes'],[
      ['id','INT AUTO_INCREMENT PK','Unique user ID'],
      ['name','VARCHAR(100)','Required'],
      ['email','VARCHAR(150) UNIQUE','University email enforced'],
      ['password','VARCHAR(255)','bcrypt hashed'],
      ['role',"ENUM('admin','student','alumni')",'Default: student'],
      ['created_at','TIMESTAMP','Default NOW()'],
    ]),
    gap(),
    hdr('alumni_profiles — Extended alumni info', HeadingLevel.HEADING_3),
    tbl(['Column','Type','Notes'],[
      ['user_id','FK → users','CASCADE delete'],
      ['graduation_year','INT','Batch year'],
      ['department','VARCHAR(100)','e.g., Computer Science'],
      ['company','VARCHAR(150)','Current employer'],
      ['designation','VARCHAR(150)','Job title'],
      ['location','VARCHAR(150)','City/Country'],
      ['linkedin','VARCHAR(255)','Profile URL'],
      ['bio','TEXT','Free text'],
    ]),
    gap(),
    hdr('events — College events', HeadingLevel.HEADING_3),
    tbl(['Column','Type','Notes'],[
      ['title','VARCHAR(200)','Required'],
      ['description','TEXT','Optional'],
      ['event_date','DATE','Required'],
      ['location','VARCHAR(200)','Venue'],
      ['created_by','FK → users','SET NULL on delete'],
    ]),
    gap(),
    hdr('jobs — Job postings', HeadingLevel.HEADING_3),
    tbl(['Column','Type','Notes'],[
      ['company','VARCHAR(150)','Required'],
      ['role','VARCHAR(150)','Job title, Required'],
      ['type','ENUM','full-time, part-time, internship, contract'],
      ['location','VARCHAR(150)','City/Remote'],
      ['deadline','DATE','Application deadline'],
      ['job_link','VARCHAR(500)','External application URL'],
      ['posted_by','FK → users','SET NULL on delete'],
    ]),
    gap(),
    hdr('messages — Direct messages', HeadingLevel.HEADING_3),
    tbl(['Column','Type','Notes'],[
      ['sender_id','FK → users','CASCADE delete'],
      ['receiver_id','FK → users','CASCADE delete'],
      ['message','TEXT','Required'],
      ['is_read','TINYINT(1)','Default 0 (unread)'],
      ['created_at','TIMESTAMP','Sent at'],
    ]),
    gap(),
    hdr('Database Indexes', HeadingLevel.HEADING_3),
    tbl(['Index','Points To'],[
      ['idx_users_email','users(email)'],
      ['idx_users_role','users(role)'],
      ['idx_alumni_profiles_uid','alumni_profiles(user_id)'],
      ['idx_alumni_grad_year','alumni_profiles(graduation_year)'],
      ['idx_alumni_department','alumni_profiles(department)'],
      ['idx_messages_sender','messages(sender_id)'],
      ['idx_messages_receiver','messages(receiver_id)'],
      ['idx_jobs_deadline','jobs(deadline)'],
      ['idx_events_date','events(event_date)'],
    ]),
    hr(),

    hdr('6. Security & Authentication System', HeadingLevel.HEADING_1),
    hdr('Authentication Flow', HeadingLevel.HEADING_3),
    b('1. User submits login form (email + password)'),
    b('2. Frontend: client-side domain check (@uohyd.ac.in)'),
    b('3. POST /api/auth/login → authController.login()'),
    b('4. Server fetches user by email from DB'),
    b('5. bcrypt.compare(password, hashed_password)'),
    b('6. If match → jwt.sign({ id, name, email, role }, JWT_SECRET, { expiresIn: "7d" })'),
    b('7. Token + user object returned to client'),
    b('8. Client: localStorage.setItem("ais_token", token)'),
    b('9. Every API call: Authorization: Bearer <token>'),
    b('10. protect() middleware: jwt.verify(token, JWT_SECRET) → req.user'),
    gap(),
    hdr('Role-Based Access Control (RBAC)', HeadingLevel.HEADING_3),
    tbl(['Feature','Student','Alumni','Admin'],[
      ['View alumni list','✅','✅','✅'],
      ['View events','✅','✅','✅'],
      ['View jobs','✅','✅','✅'],
      ['Send messages','✅','✅','✅'],
      ['Update own alumni profile','❌','✅','❌'],
      ['Post jobs','❌','✅','✅'],
      ['Edit own posted job','❌','✅','✅ (if posted)'],
      ['Delete any job','❌','❌','✅'],
      ['Create/Edit/Delete events','❌','❌','✅'],
      ['View admin dashboard stats','❌','❌','✅'],
      ['Manage users (role/delete)','❌','❌','✅'],
      ['Helpdesk — initiate chat','❌','❌','✅'],
      ['Helpdesk — reply to admin','✅','✅','✅'],
    ]),
    gap(),
    hdr('Security Features', HeadingLevel.HEADING_3),
    b('bcrypt password hashing (salt rounds = 10)'),
    b('JWT tokens expire in 7 days'),
    b('University email enforcement (@uohyd.ac.in) at both register + login'),
    b('Ownership checks on job edits — only the original poster can edit'),
    b('Admin self-protection — admin cannot delete or change their own account from UI'),
    b('Parameterized SQL queries everywhere — prevents SQL injection'),
    hr(),

    hdr('7. Complete API Reference', HeadingLevel.HEADING_1),
    p('Base URL: http://localhost:5000/api'),
    gap(),
    tbl(['Group','Method','Endpoint','Auth','Description'],[
      ['Auth','POST','/auth/register','Public','Register new student or alumni account'],
      ['Auth','POST','/auth/login','Public','Login — returns JWT token + user object'],
      ['Auth','GET','/auth/me','Any user','Get authenticated user profile'],
      ['Auth','GET','/auth/admin-id','Public','Get first admin ID & name (helpdesk widget)'],
      ['Alumni','GET','/alumni/','Any user','List all alumni (?name=, ?batch=, ?department=)'],
      ['Alumni','GET','/alumni/:id','Any user','Get single alumni full profile'],
      ['Alumni','GET','/alumni/profile/me','Alumni','Get own alumni profile'],
      ['Alumni','PUT','/alumni/profile','Alumni','Update own alumni profile'],
      ['Events','GET','/events/','Any user','List all events'],
      ['Events','POST','/events/','Admin','Create new event'],
      ['Events','PUT','/events/:id','Admin','Update event'],
      ['Events','DELETE','/events/:id','Admin','Delete event'],
      ['Jobs','GET','/jobs/','Any user','List all jobs'],
      ['Jobs','POST','/jobs/','Alumni / Admin','Post a new job'],
      ['Jobs','PUT','/jobs/:id','Owner / Admin','Update job (ownership enforced)'],
      ['Jobs','DELETE','/jobs/:id','Owner / Admin','Delete job (ownership enforced)'],
      ['Messages','POST','/messages/','Any user','Send a message { receiver_id, message }'],
      ['Messages','GET','/messages/inbox','Any user','Get inbox grouped by sender, latest first'],
      ['Messages','GET','/messages/conversation/:userId','Any user','Get full thread + mark as read'],
      ['Admin','GET','/admin/dashboard','Admin','System-wide stats (users, events, jobs, messages)'],
      ['Admin','GET','/admin/users','Admin','List all registered users'],
      ['Admin','PUT','/admin/users/:id/role','Admin','Change a user role'],
      ['Admin','DELETE','/admin/users/:id','Admin','Permanently delete a user'],
      ['Admin','GET','/admin/helpdesk','Admin','List users who messaged admin (unread count)'],
      ['Admin','GET','/admin/helpdesk/:userId','Admin','Full conversation between admin and user'],
    ]),
    hr(),

    hdr('8. Frontend Pages', HeadingLevel.HEADING_1),
    tbl(['Page','File','Access','Description'],[
      ['Landing','index.html','All','Auto-redirects to dashboard or login based on auth'],
      ['Login','login.html','Public','JWT login form with validation'],
      ['Register','register.html','Public','Student / alumni registration (domain restricted)'],
      ['Dashboard','dashboard.html','All','Personal greeting, role badge, quick nav links'],
      ['Alumni Directory','alumni.html','All','Filterable table + profile modal + inline profile edit'],
      ['Events','events.html','All','Event cards; admin create/edit form appears on-page'],
      ['Job Board','jobs.html','All','Job cards with type badge, deadline, apply link; post/edit for alumni'],
      ['Messages','messages.html','All','Split-pane: inbox list + chat thread; smart recipient pre-fill'],
      ['Admin Panel','admin.html','Admin only','Stats cards + user table + helpdesk chat panel'],
    ]),
    hr(),

    hdr('9. Key Features Detail', HeadingLevel.HEADING_1),
    tbl(['Module','Feature','Detail'],[
      ['Alumni Directory','Search','Filter by name, batch year, department'],
      ['Alumni Directory','Profile Modal','View company, designation, location, LinkedIn, bio'],
      ['Alumni Directory','Message Button','One-click redirect to Messages with pre-filled recipient'],
      ['Alumni Directory','Profile Edit','Alumni can update their own profile inline'],
      ['Messaging System','Recipient Field','Read-only when accessed via Alumni Directory redirect'],
      ['Messaging System','Recipient Banner','Shows "Sending message to: <Name>" for context'],
      ['Messaging System','Auto-focus','Message input auto-focused on redirect from alumni page'],
      ['Messaging System','Chat UI','Split-pane inbox + bubble-style conversation thread'],
      ['Messaging System','Read Status','is_read flag updated when conversation is opened'],
      ['Admin Helpdesk','Inbox','Lists all users who have messaged the admin'],
      ['Admin Helpdesk','Unread Badge','Shows count of unread messages per user'],
      ['Admin Helpdesk','+ New Button','Admin can start a conversation with any student/alumni first'],
      ['Admin Helpdesk','User Picker','Search dropdown with name, role, email of all non-admin users'],
      ['Admin Helpdesk','Auto Refresh','Helpdesk sidebar refreshes every 30 seconds'],
      ['Admin Helpdesk','Empty State','Friendly prompt when admin opens a user with no messages yet'],
      ['Job Board','Post','Alumni and admin can post with company, role, type, location, deadline'],
      ['Job Board','Job Link','External URL — redirects to actual application portal'],
      ['Job Board','Ownership','Edit/Delete only visible to original poster or admin'],
      ['Job Board','Type Badge','Full-Time, Part-Time, Internship, Contract'],
    ]),
    hr(),

    hdr('10. Getting Started', HeadingLevel.HEADING_1),
    hdr('Prerequisites', HeadingLevel.HEADING_3),
    tbl(['Requirement','Minimum Version'],[
      ['Node.js','v16+'],['MySQL','v8+'],['npm','v8+'],
    ]),
    gap(),
    hdr('Step 1 — Clone the Repository', HeadingLevel.HEADING_3),
    mono('git clone <repository-url>'),
    mono('cd alumni-system'),
    hdr('Step 2 — Install Dependencies', HeadingLevel.HEADING_3),
    mono('npm install'),
    hdr('Step 3 — Configure .env File', HeadingLevel.HEADING_3),
    mono('DB_HOST=localhost   |  DB_PORT=3306   |  DB_NAME=alumni_db'),
    mono('DB_USER=root        |  DB_PASSWORD=your_mysql_password'),
    mono('JWT_SECRET=your_secret_key   |  JWT_EXPIRE=7d'),
    mono('PORT=5000           |  NODE_ENV=development'),
    hdr('Step 4 — Set Up the Database', HeadingLevel.HEADING_3),
    mono('npm run db:setup'),
    b('Creates the alumni_db database'),
    b('Runs schema.sql — creates all 5 tables + 9 indexes'),
    b('Seeds the default admin account'),
    hdr('Step 5 — Start the Server', HeadingLevel.HEADING_3),
    mono('npm run dev      # Development (auto-restart)'),
    mono('npm start        # Production'),
    hdr('Step 6 — Open in Browser', HeadingLevel.HEADING_3),
    mono('http://localhost:5000'),
    hr(),

    hdr('11. Environment Variables', HeadingLevel.HEADING_1),
    tbl(['Variable','Default','Required','Description'],[
      ['DB_HOST','localhost','Yes','MySQL server hostname'],
      ['DB_PORT','3306','Yes','MySQL server port'],
      ['DB_NAME','alumni_db','Yes','Target database name'],
      ['DB_USER','root','Yes','MySQL username'],
      ['DB_PASSWORD','(empty)','Yes','MySQL password'],
      ['JWT_SECRET','—','Yes','Secret key for signing JWT tokens'],
      ['JWT_EXPIRE','7d','No','Token expiry (7d, 24h, etc.)'],
      ['PORT','5000','No','HTTP server port'],
      ['NODE_ENV','development','No','Environment mode'],
    ]),
    hr(),

    hdr('12. Default Credentials', HeadingLevel.HEADING_1),
    tbl(['Field','Value'],[
      ['Email','admin@alumni.com'],
      ['Password','Admin@123'],
      ['Role','admin'],
    ]),
    gap(),
    p('⚠️  Change the admin password after first login in any production environment.'),
    hr(),

    hdr('13. NPM Scripts', HeadingLevel.HEADING_1),
    tbl(['Script','Command','Description'],[
      ['npm start','node server.js','Start production server'],
      ['npm run dev','nodemon server.js','Start dev server with auto-reload'],
      ['npm run db:setup','node scripts/setupDb.js','Create DB schema + seed admin'],
    ]),
    hr(),

    hdr('14. Important Notes', HeadingLevel.HEADING_1),
    tbl(['Topic','Detail'],[
      ['Email Domain','Self-registration restricted to @uohyd.ac.in. Admins bypass this on login.'],
      ['Alumni Profile','Auto-created on registration (alumni) or when admin promotes student → alumni.'],
      ['Message Read Status','Marked is_read = 1 automatically when conversation thread is opened.'],
      ['Helpdesk Refresh','Admin helpdesk sidebar polls every 30 seconds for new messages.'],
      ['Job Ownership','Edit/Delete rendered only if posted_by === currentUser.id or role is admin.'],
      ['Admin Initiate Chat','Admin can open a conversation with any student/alumni first via + New picker.'],
      ['Recipient Lock','When navigating to Messages via Alumni Directory, recipient ID is readonly.'],
      ['Connection Pool','MySQL pool is set to 10 connections with unlimited queue.'],
      ['Static Hosting','The public/ folder is served directly by Express — no separate frontend build.'],
      ['Admin Self-Guard','Admin cannot delete/modify their own account via the UI.'],
    ]),
    hr(),

    new Paragraph({ children: [new TextRun({ text: 'MIT License  |  Alumni Information System  |  University of Hyderabad', size: 18, color: '888888' })], alignment: AlignmentType.CENTER, spacing: { before: 400 } }),
  ]}]
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('Alumni_Information_System.docx', buf);
  console.log('✅  Alumni_Information_System.docx created successfully!');
}).catch(e => console.error('❌ Error:', e.message));
